name: CypressOnChrome

on: push

jobs:
  Chrome:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RunOnChrome
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/Assignment-4/Program-3.cy.js
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
           name: cypress-execution-report
           path: cypress/reports/html
           retention-days: 10
        
